### ISSUE TITLE
Use themed colors (green/red/yellow)

### ISSUE THREAD

**Issue by Alexey-T** [OlehL/cuda_differ#10]
Syntax theme has 3 colors: green/red/yellow. e.g. see any diff file with changed/deleted/added lines.

cuda_csv_hilite
```
_theme = app_proc(PROC_THEME_SYNTAX_DATA_GET, '')

def _theme_item(name):
    for i in _theme:
        if i['name']==name:
            return i['color_font']
    return 0x808080


option_colors_themed = 'Id,Id1,Id2,Id3,Id4,IdVar,String,Comment,Comment2,Label,Color'

        if option_use_theme_colors:
            COLOR_COMMA = _theme_item('Symbol')
            PALETTE = [_theme_item(s) for s in option_colors_themed.split(',')]
```

**Comment by OlehL** [comment]
Я думал что эти цвета должны быть с "color_back" а не с "color_font" тогда не возникнет ситуаций где заливка будет сливаться с каким то текстом (так как при сравнении подсветка Лексера активная для более привычного чтения). Но я не нашел в темах green/red/yellow цветов которые я бы мог использовать для этого. Если знаешь какие цвета можно использовать - то поставлю их по умолчанию.
Сейчас я дал возможность пользователю самому выбирать цвета которые ему больше нравятся. Это нужно сделать только один раз после установки плагина или при изменении темы, что обычно бывает очень редко.

**Comment by Alexey-T** [comment]
В теме есть три цвета- они юзаются лексером Diff- можешь посмотреть какие эл темы в файле diff.cuda-lexmap 

 И поправишь пример чтоб он читал не color_font а color_back из этих трёх элементов

**Comment by OlehL** [comment]
Сделал по умолчанию цвета из темы, но пользователь может изменить цвет в файле настроек, если текущий ему не нравится.
