### ISSUE TITLE
bookmarks?

### ISSUE THREAD

**Issue by Alexey-T** [OlehL/cuda_differ#12]
может лучше дать букмарки (3х видов)?
марки могут иметь флаг "не показывать в GoTo bookmark dialog".
```
BOOKMARK_SET: Sets bookmark.

    Param "nline": int: line index of bookmark.
    Param "nkind": int: kind of bookmark: 1 means usual bookmark with usual color and icon. Other kind values mean custom bookmark, which must be setup via BOOKMARK_SETUP.
    Param "text": str: tooltip, shown when mouse moves over bookmark gutter icon.
    Param "auto_del": bool: auto delete bookmark on deleting its text line.
    Param "show": bool: show bookmark in "Go to bookmark" dialog.
    Param "tag": int: some value attached to bookmark.
```

Наверно лучше так а не декор

**Comment by OlehL** [comment]
В чем отличия от decor?

**Comment by Alexey-T** [comment]
Букмарк краст всю строку до конца экрана и Только Фон

**Comment by OlehL** [comment]
Если я буду использовать bookmarks, то как тогда пользователь сможет установить собственные bookmarks и как тогда будет работать CudaLinter? Для одной строки можно установить один bookmark.
Уже сейчас bookmarks перегружены.
Для примера: если установить bookmark на строку и при редактировании cudaLinter подсветит ту же строку, то bookmark пользователя исчезнет. И наоборот если попробовать поставить bookmark на строку, которою подсветил CudaLinter, то пользователь перебивает bookmark CudaLinter(и то со второго раза).
Если я начну организовывать подсветку через bookmarks то будет еще больше бардак.

Думаю, что лучше будет расширить API и дать attr возможность красить всю сроку.
Также я не уверен, что поведение attr не допускать несколько attrs в одной позиции является правильной.
Например если один плагин будет красить фон, а в другом плагине реализовано окраска текста (как в csv_hilite), то второй будет мешать работе первого.

**Comment by Alexey-T** [comment]
Возникла идея. дать "низкоприоритетные букмарки" во 2м списке. они рисуются 
только если нет обычных букмарков на той же строке.

**Comment by OlehL** [comment]
> Например если один плагин будет красить фон, а в другом плагине реализовано окраска текста (как в csv_hilite), то второй будет мешать работе первого.

Как "низкоприоритетные букмарки" решат эту проблему?

**Comment by Alexey-T** [comment]
такие букмарки лежат в списке bookmarks2, и никак не мешают маркам из обычного списка. если для строки есть обычная марка, она рисуется. если нет- то ищется марка из bookmarks2 и рисуется.

уже написал код в ядре. осталось дать АПИ в Куд

**Comment by Alexey-T** [comment]
http://wiki.freepascal.org/CudaText_API#bookmark
описано в середине

**Comment by OlehL** [comment]
то есть если плаг закрасит строку через bookmark2, а потом пользователей поставит обычный bookmark, то будет виден обычный. Потом если пользователь снимет обычный bookmark станет виден bookmark2. Я правильно понял?

**Comment by Alexey-T** [comment]
да

**Comment by OlehL** [comment]
так ОК

**Comment by Alexey-T** [comment]
(закроем когда заюзаешь АПИ)

**Comment by Alexey-T** [comment]
Beta 1.73.1 with BOOKMARK2_* api

**Comment by OlehL** [comment]
@Alexey-T  test pls.

**Comment by Alexey-T** [comment]
bookmark2 желтые есть - и поверх них старые красные-зеленые attr.  Хмм

**Comment by Alexey-T** [comment]
![screenshot from 2019-02-01 00-51-56](https://user-images.githubusercontent.com/4154978/52087860-9cb91c80-25bb-11e9-964c-3edb702601c6.png)

**Comment by Alexey-T** [comment]
то что целиком новые и целиком стёртые строки надо красить целиком красным-зелёным.

**Comment by Alexey-T** [comment]
Тогда часть букмарк2 надо дать красным-зелёным и аттр для них убрать

**Comment by Alexey-T** [comment]
Целиком новые и целиком удаленные строки- надо красить bookmarks2- цвета красный и зеленый. И не класть на них аттр. А измененные- как и сейчас. 

так будет похоже на VSCode и тд.

**Comment by OlehL** [comment]
fixed in  395edb9

**Comment by Alexey-T** [comment]
Tkx
