### ISSUE TITLE
macOS- wrong folders created

### ISSUE THREAD

**Issue by Alexey-T** [OlehL/cuda_differ#15]
под Мак было открыто 2 файла (еще без плагина).
вызвал плагин. выбрал из комбов эти же имена - которые открыты.

итого. он создал копии файлов в lowercase папках. 
было имя /Users/user/Documents/nnn, ( ~ значит /Users/user )
он создал копию в /users/user/documents/nnn.

вот
![dif-mac2](https://user-images.githubusercontent.com/4154978/52008709-46c47600-24e2-11e9-9c0f-dfbd4667cc57.png)

**Comment by Alexey-T** [comment]
в истории видно что пара файлов есть и в старой папке и в новой папке lowercase.

**Comment by OlehL** [comment]
Сейчас должно заполнять правильно (на win 10 ok). Сделай пожалуйста тест на macOS.

**Comment by Alexey-T** [comment]
Fixed, tks
