### ISSUE TITLE
Opts needed: sync_scroll_vert, sync_scroll_horz

### ISSUE THREAD

**Issue by Alexey-T** [OlehL/cuda_differ#17]
в Мак что то кривое с sync scroll - там дергается все туда сюда. так что опция нужна. по горизонтали силнее дергается

**Comment by OlehL** [comment]
неуверенно из-за gaps

**Comment by Alexey-T** [comment]
Там что то временно в ОС было, и с горизонт скроллом хотя Гепс не виноват

**Comment by Alexey-T** [comment]
хмм, в Ини файлах принято булево писать как 0 или 1 :)
