### ISSUE TITLE
wrong hiliting of deleted/added items

### ISSUE THREAD

**Issue by Alexey-T** [OlehL/cuda_differ#2]
тут не красит одну красную и одну зеленую линию. хотя gaps стоят ОК.
![screenshot from 2019-01-28 01-53-43](https://user-images.githubusercontent.com/4154978/51808038-c31b4700-229f-11e9-9168-7e5fb00f3a8f.png)

**Comment by Alexey-T** [comment]
2 files
[tests.zip](https://github.com/OlehL/cuda_differ/files/2802384/tests.zip)

**Comment by OlehL** [comment]
fixed

**Comment by OlehL** [comment]
@Alexey-T pls test it

**Comment by Alexey-T** [comment]
Fixed, good
