### ISSUE TITLE
strange decor for this diff

### ISSUE THREAD

**Issue by Alexey-T** [OlehL/cuda_differ#25]
правый файл. строки 8 и 9 изменены одинаково но decor стоит разный - зел и желт.
почему?
![screenshot from 2019-02-04 21-46-00](https://user-images.githubusercontent.com/4154978/52229634-713d7700-28c6-11e9-8b30-1a31204139df.png)

**Comment by Alexey-T** [comment]
[test.zip](https://github.com/OlehL/cuda_differ/files/2829368/test.zip)

**Comment by OlehL** [comment]
проблема была в порядке прорисовки для строк где есть несколько изменений. Для 8 строки это replace и delete.

**Comment by Alexey-T** [comment]
Отлично. выложу плагин когда выложу Куд. это еще день-два..
