### ISSUE TITLE
Config item

### ISSUE THREAD

**Issue by Alexey-T** [OlehL/cuda_differ#3]
пункт у нас обычно называют Config (хотя бы Settings  c -s)

color_changed_line = #a0a000
color_detail_add = #00a282
color_detail_del = #cD8087

опции может лучше назвать? changed=, added=, deleted=

**Comment by OlehL** [comment]
fix in  2fcf4d7

**Comment by OlehL** [comment]
нужно удалить старий файл cuda_differ.ini
