### ISSUE TITLE
add check?

### ISSUE THREAD

**Issue by Alexey-T** [OlehL/cuda_differ#31]
Релизнул плагин.

    def on_scroll(self, ed_self):

тут может добавить проверку get_prop(PROP_SPLIT) - даст '-' если нет сплита.

**Comment by Alexey-T** [comment]
Неточно сказал, Апи даёт 2 tuple, где элемент 0 это минус , если таб не сплитнут

**Comment by Alexey-T** [comment]
т.е. 
p = ed.get_prop(PROP_SPLIT)
if p[0]=='-':

**Comment by OlehL** [comment]
понял, исправлю
