### ISSUE TITLE
Ini details

### ISSUE THREAD

**Issue by kvichans** [OlehL/cuda_differ#34]
1. Как задавать цвета?
```ini
changed=
added=
deleted=
```
Можно ли задавать *прозрачные* цвета, то есть содержащие альфа-компоненту?

2. Что означает
```ini
enable_scroll_default=1
```
и какие еще возможны значения?

**Comment by Alexey-T** [comment]
#rgb
#rrggbb

0 или 1
Синхронный скролл в паре

**Comment by kvichans** [comment]
Сейчас сихро-скролл не перемещает каретку. Это неудобно - перешел в соседний файл нажал на стрелку и потерял скрол. Можно это исправить?

**Comment by OlehL** [comment]
> Сейчас синхро-скролл не перемещает каретку. Это неудобно - перешел в соседний файл нажал на стрелку и потерял скрол. Можно это исправить?
Я это добавлю в будущем.

**Comment by Alexey-T** [comment]
?

**Comment by kvichans** [comment]
Уже можно проверять?

**Comment by Alexey-T** [comment]
Что теряется каретка с экрана , не менял. Сделайте пач?

**Comment by kvichans** [comment]
нет

**Comment by Alexey-T** [comment]
Закроем?

**Comment by kvichans** [comment]
зачем? проблема-то осталась

**Comment by Alexey-T** [comment]
Проверьте опцию keep caret visible - но она может давать каретку на строку выше экрана, это поправлю в бете куды

**Comment by Alexey-T** [comment]
@kvichans Решили?

**Comment by OlehL** [comment]
Изменена опция для синхронизации каретки в 9f99f4e2a7ced81af54479fa648ed7039491a139
