### ISSUE TITLE
Where filenames are stored?

### ISSUE THREAD

**Issue by kvichans** [OlehL/cuda_differ#35]
Вижу, что диалог выбора файлов, запомнил предыдущие настройки. 
Где хранится эта информация?

**Comment by Alexey-T** [comment]
Только в памяти

**Comment by kvichans** [comment]
Ужас. Нужно сохранять хотя бы по 20 использованных файлов (два списка - правые и левые)

**Comment by Alexey-T** [comment]
Плюсую :)

**Comment by Alexey-T** [comment]
Только единый список имхо

**Comment by kvichans** [comment]
> единый список

Фу

**Comment by OlehL** [comment]
Поддерживаю один список, так как тогда пользователь в следующий раз может использовать файлы с истории в левой или в правой части таба.
Сейчас такая же логика для уже открытых файлов в других табах.

**Comment by kvichans** [comment]
Один список - это уже хорошо.
Два списка - идеально

**Comment by Alexey-T** [comment]
решено - в pull request. @OlehL примени плс.

**Comment by Alexey-T** [comment]
@OlehL @kvichans закройте

**Comment by kvichans** [comment]
Два часа назад установил из ГХ в Куд. Второй файл не запомнился - даже не появился в списке.
Закрывать рано?

**Comment by Alexey-T** [comment]
Какой набор табов был по группам? Какие имена и где

**Comment by kvichans** [comment]
![image](https://user-images.githubusercontent.com/7419630/56668917-00ce1700-66b9-11e9-89f3-03446c8baf13.png)
Файл указанный вторым уже открыт в табе 6. Он не запоминается.
Кроме того список запомненных файлов не перестраивается от ввода. Я сегодня вводил только эти два имени, но первый оказался далеко от начала списка.

**Comment by Alexey-T** [comment]
попробуйте сделать пач.
я не знаю что надо.
ui.py
class DifferDialog:
        items = "\t".join(open_files+file_history.items)

видно что вверх списка лезут открытые файлы, и то что открывалось (file_history) идет потом.
то что второе имя пусто- тоже видно в коде

**Comment by Alexey-T** [comment]
?

**Comment by kvichans** [comment]
Здесь остался не технический вопрос. Дело вкуса. 
Мне(!) странно, что все отрытые файлы в списке для комбо попали перед сохраненными (=предыдущими примененными).
Может быть комбо здесь мало уместен - лучше дать кнопку, которая покажет фильтруемый dlg_menu

**Comment by Alexey-T** [comment]
Имхо меню тут будет не к месту
Может сделаете опцию чтоб порядок в комбо был другой ?

**Comment by kvichans** [comment]
нет

**Comment by Alexey-T** [comment]
Закроем?
