### ISSUE TITLE
What command Refresh does?

### ISSUE THREAD

**Issue by kvichans** [OlehL/cuda_differ#36]

**Comment by Alexey-T** [comment]
После правок файлов, ещё раз сравнивает

**Comment by kvichans** [comment]
Уточняю вопрос. Повторное сравнение *открытых* файлов выполняется по их дисковым состояниям или по текущему состоянию в табе?
ИМХО Ничего не мешает брать для сравнения текущее состояние

**Comment by Alexey-T** [comment]
По текущему
