### ISSUE TITLE
(wish) Jump to next/prev interesting lines

### ISSUE THREAD

**Issue by kvichans** [OlehL/cuda_differ#37]
Можно ли добавить команды для перемещения обеих кареток с след/пред месту, где сравнение дало нетривиальный результат?

**Comment by Alexey-T** [comment]
Плюсую, это нужно если есть н правок где то в местах огромного файла

**Comment by OlehL** [comment]
Согласен

**Comment by Alexey-T** [comment]
решено в pull req.
