### ISSUE TITLE
(wish) Fill gaps

### ISSUE THREAD

**Issue by kvichans** [OlehL/cuda_differ#38]
Можно ли дать раскраску для *пропусков строк*?

Пример
Так сравнивает плагин
![default](https://user-images.githubusercontent.com/7419630/52417125-31f86b80-2afc-11e9-97ce-a28bb25a4320.png)
Так сравнивает WinMerge
![default](https://user-images.githubusercontent.com/7419630/52417159-49375900-2afc-11e9-969f-40f4972da23e.png)

Во втором случае искусственные сдвиги (перед 2-й слева, 4-й справа) хорошо видны

**Comment by Alexey-T** [comment]
Плюсую

**Comment by Alexey-T** [comment]
API не умеет это

**Comment by kvichans** [comment]
А разве do_gap не получится доработать в ядре?

**Comment by Alexey-T** [comment]
сорри- плагин сам выбирает цвет gaps.

**Comment by kvichans** [comment]
> API не умеет это

> плагин сам выбирает цвет gaps.

Это как?

**Comment by Alexey-T** [comment]
Про Апи я ошибся

**Comment by kvichans** [comment]
:) Тогда чистый виш на еще один цвет в настройках

**Comment by Alexey-T** [comment]
Плюсую

**Comment by Alexey-T** [comment]
Какой элемент syntax theme взять для gaps? Счас берутся LightBG1...3

**Comment by kvichans** [comment]
Почему три цвета нужно задавать явно
```ini
[colors]
changed=
added=
deleted=
```
А для gap брать из темы?

**Comment by kvichans** [comment]
Похоже нужен новый АПИ-диалог, аналогичный `dlg_color` - чтобы подставлять имена цветов из *темы*.

**Comment by Alexey-T** [comment]
потому что если задано "пусто"- берется из темы.

**Comment by OlehL** [comment]
> Можно ли дать раскраску для _пропусков строк_?

Да, добавлю
