### ISSUE TITLE
(wish) More compare options 

### ISSUE THREAD

**Issue by kvichans** [OlehL/cuda_differ#39]
Есть ли возможность более тонкой настройки поиска различий?

Например
1. Можно ли игнорировать разницу в последовательных пробельных символах: пробелы, пустые строки и т.п.
2. Можно ли игнорировать разницу Win/Unix/Max концов строк
3. Всегда ли выполняется поиск *перемещенных блоков* (тяжелая, не всегда нужная задача)?

**Comment by Alexey-T** [comment]
2. Вроде уже

**Comment by kvichans** [comment]
2. Как "уже" - где эта настройка?

**Comment by Alexey-T** [comment]
2. Он просто игнорит это

**Comment by kvichans** [comment]
2. Жесткое умолчание = зло

**Comment by Alexey-T** [comment]
Можете помоч? Найти в питоновой difflib эти опции. Где они?

**Comment by kvichans** [comment]
Не нашел

**Comment by OlehL** [comment]
1. Пока нельзя.
2. Концы строк игнорируются полностью.
3. Пока всегда но сделаю опционально.

**Comment by Alexey-T** [comment]
Oleh, отмена с Clips panel (не надо)
