### ISSUE TITLE
(wish) Color chooser in config dlg

### ISSUE THREAD

**Issue by kvichans** [OlehL/cuda_differ#41]
Хорошо бы задавать цвета в диалоге и сразу видеть пример, как они будут применяться

**Comment by kvichans** [comment]
@Alexey-T Внутри диалога можно будет в editor-контрол всунуть два файла?

**Comment by Alexey-T** [comment]
Какого диалога?

**Comment by kvichans** [comment]
dlg_proc

**Comment by Alexey-T** [comment]
Не понял вопросы

**Comment by kvichans** [comment]
Вторая попытка. 
- В диалоге Настройки differ дать контрол с редактором, в котором в RO-режиме показывать как будут действовать цвета. 
- Можно ли в такой контрол поместить сразу два файла, то есть сделать как в табе?
- Цвета настраивать здесь же через вызовы `dlg_color()`.

**Comment by Alexey-T** [comment]
Нет такого диалога, есть открытие ини для правок

**Comment by Alexey-T** [comment]
И не надо его делать, т к трудно

**Comment by kvichans** [comment]
"Трудно"? Если вы про автора плага, то согласен. Но есть помощники (это я на себя намекаю), которые любят строгать полезные диалоги.

**Comment by kvichans** [comment]
Так что вопрос про 2in1 для контрола не лишен интереса

**Comment by Alexey-T** [comment]
Если Олег примет патч с диалогом, я рад. Да, вы можете сделать в длг два или семь контролов editor

**Comment by OlehL** [comment]
Пока не вижу необходимости для сложного диалога.
В будущем планирую добавить простой диалог с настройками, которые можно будет менять на лету.
Сейчас Пользователь может менять настройки в ini файле и использовать команду Refresh для отображения этих изменений.

**Comment by Alexey-T** [comment]
Закроем?
