### ISSUE TITLE
Smooth scroll API

### ISSUE THREAD

**Issue by Alexey-T** [OlehL/cuda_differ#47]
Cud 1.78.5 будет иметь новое апи для per pixel scroll
Надо заюзать- пока синк скролла крив (т.к. юзается per line scroll)

* PROP_SCROLL_VERT: int: approximate vertical scroll position. Index in WrapInfo list, you can read this list via get_wrapinfo().
* PROP_SCROLL_HORZ: int: approximate horizontal scroll position. Same as PROP_COLUMN_LEFT.
* PROP_SCROLL_VERT_SMOOTH: int: smooth vertical scroll position. In pixels.
* PROP_SCROLL_HORZ_SMOOTH: int: smooth horizontal scroll position. In pixels.
* PROP_SCROLL_VERT_INFO: int: dict with all available info about vertical scroll.
* PROP_SCROLL_HORZ_INFO: int: dict with all available info about horizontal scroll.

**Comment by Alexey-T** [comment]
заменил в scroll.py апи на новое. Работает ок. Синк-скролл Ок.
пока нужно еще мне доделать- для гепов после 1й строки и перед 1й строкой.

**Comment by Alexey-T** [comment]
послал pull request.

**Comment by OlehL** [comment]
принял
