### ISSUE TITLE
gutter decoration

### ISSUE THREAD

**Issue by Alexey-T** [OlehL/cuda_differ#5]
Хорошо бы через ed.decor() стаить иконки - 3х цветов
http://wiki.freepascal.org/CudaText_API#decor

**Comment by OlehL** [comment]
Я думал об этом раньше. Но пока не представляю как это будет выглядеть. Если есть какой-то наглядный пример как это должно выглядеть, тогда сделаю.

Сейчас могу добавить знаки "+" и "-".
В других редакторах обычно дополнительно закрашенные еще номера строк, но для этого нужно дополнительное api.
![default](https://user-images.githubusercontent.com/26593946/51900591-68c4d800-23be-11e9-850b-a8adcbe13f6e.png)

**Comment by Alexey-T** [comment]
наверно показать знаки (не иконки)- зеленый плюс (взять цвет темы), красный минус, желтый *

**Comment by Alexey-T** [comment]
Как взять цветы темы- #10

**Comment by OlehL** [comment]
Добавил в  8277535
