### ISSUE TITLE
Json config 

### ISSUE THREAD

**Issue by Alexey-T** [OlehL/cuda_differ#53]
мы с @kvichans хотим сделать диалог опций, который заработает через плагин Option Editor- надо только иметь конфиг в Json. ОК на переделку конфига плагина из ini в json?

**Comment by kvichans** [comment]
Я бы не понял, что пишет Алексей.
Задумка такая
- Подменить хранение опций вашего плагина: с *.ini на user.json
- Добавить еще один json с описанием опций (его формат есть в вики)
- В результате не нужно будет создавать новый диалог для просмотра/изменения ваших опций, так как можно будет использовать диалог из  cuda_options_editor 
- Сейчас это диалог показывает опции Куд и плагина ПоискПоФайлам

**Comment by kvichans** [comment]
От вас мы с Алексеем ждем согласия на патч, который заменит ini-хранение, на json-хранение

**Comment by Alexey-T** [comment]
я с телефона писал, вышло оч. кратко.

**Comment by Alexey-T** [comment]
@kvichans Float option - в диапазоне [0,1]
название: Measure of the sequences' similarity

**Comment by kvichans** [comment]
Лучше сразу [в формате](http://wiki.freepascal.org/CudaText_API#Options_Editor) для options_editor. Если формат узок - есть повод его расширять

**Comment by Alexey-T** [comment]
надо расширять.
- надо тип float (не знаю как дать диапазон)
- надо тип int (и диапазон)

**Comment by OlehL** [comment]
Я за

**Comment by kvichans** [comment]
Попробую сделать Pull Req (первый раз!)

**Comment by Alexey-T** [comment]
к моему репо лучше, в акаунте моем.
