### ISSUE TITLE
Why 'ini_time'?

### ISSUE THREAD

**Issue by kvichans** [OlehL/cuda_differ#54]
Вижу что время модификации ini-файла хранится среди настроек и используется в каком-то трюке
```python
    def config(self):
        ini_time = os.path.getmtime(INIFILE)
        theme_name = ct.app_proc(ct.PROC_THEME_SYNTAX_GET, '')
        if self.cfg.get('ini_time') == ini_time \
                and self.cfg.get('theme_name') == theme_name:
            return
        self.cfg = self.get_config()
```
Поясните
Если самого ini-файла не будет, то как этот трюк провернуть?

**Comment by OlehL** [comment]
После "Refresh" или "Choise files" загружает настройки из ini файла если была изменена тема или редактировались настройки пользователем

**Comment by kvichans** [comment]
@OlehL Можно ли обойтись без этого трюка? Или внутри трюка без ini-файла?

**Comment by OlehL** [comment]
для json можно пока без. Потом добавлю по возможности

**Comment by kvichans** [comment]
ок

**Comment by kvichans** [comment]
Хранение будет в отдельном файле `cuda_differ.json` - трюк можно будет сохранить

**Comment by Alexey-T** [comment]
Закроем?
