### ISSUE TITLE
Meta-info for options

### ISSUE THREAD

**Issue by kvichans** [OlehL/cuda_differ#55]
Нужно согласовать описание параметров.
Структура json описна в [вики](http://wiki.freepascal.org/CudaText_API#Options_Editor).
```python
[
    {"opt":"differ.changed_color",
     "cmt":"???",
     "def":"",      "frm":"str",    "chp":"colors",
    },
    {"opt":"differ.added_color",
     "cmt":"???",
     "def":"",      "frm":"str",    "chp":"colors",
    },
    {"opt":"differ.deleted_color",
     "cmt":"???",
     "def":"",      "frm":"str",    "chp":"colors",
    },
    {"opt":"differ.gap_color",
     "cmt":"???",
     "def":"",      "frm":"str",    "chp":"colors",
    },
    {"opt":"differ.enable_scroll_default",
     "cmt":"???",
     "def":true,    "frm":"bool",   "chp":"config",
    },
    {"opt":"differ.compare_with_details",
     "cmt":"???",
     "def":true,    "frm":"bool",   "chp":"config",
    },
    {"opt":"differ.ratio",
     "cmt":"???",
     "def": 0.75,   "frm":"float",  "chp":"config",
    },
]
```
1. Жду описаний для опций, то есть значений у `"cmt"`.
2. Пока в этой структуре нет формально заданных ограничений на значения, можно их указывать внутри описания `"cmt"`.
3. Пока цвета будут типа `str`. Потом поменяю тип, например, на `rgb` и диалог будет их показывать и менять.

**Comment by kvichans** [comment]
Редактор работает
![image](https://user-images.githubusercontent.com/7419630/56712586-b2ac2880-6737-11e9-870a-4be9a5a8d387.png)

Нужны описания опций

**Comment by Alexey-T** [comment]
- Color of changed lines
- Color of added lines
- Color of deleted lines
- Color of inter-line gap background
- Enable automatical sync-scrolling in both compared files
- Detailed compare
- Measure of the sequences’ similarity, float value in the range [0, 1]

**Comment by kvichans** [comment]
ok

**Comment by kvichans** [comment]
Спрятал контролы/колонки про лексеры и тек.файл
![image](https://user-images.githubusercontent.com/7419630/56730156-d71bfb00-675f-11e9-805d-f2446349d264.png)
Осталось 
- Перенаправить хранение из user.json в differ.json
- Добавить отображение и выбор цвета

А про встраивание ограничений (диапазоны) нужно думать. Будет видимо позже

**Comment by Alexey-T** [comment]
С префиксом, cuda_differ.json

**Comment by kvichans** [comment]
Я же делаю полуфабрикат. Конкретные имена выбирайте сами

**Comment by Alexey-T** [comment]
я и поправил имя.

**Comment by kvichans** [comment]
Я перед PR сделаю список имен, которые нужно будет утвердить/поправить

**Comment by Alexey-T** [comment]
Закроем?
