### ISSUE TITLE
Sync view is not synced here

### ISSUE THREAD

**Issue by Alexey-T** [OlehL/cuda_differ#68]
Даю 2 файла -проекты Лазарус. с середины экрана на скрине идет рассинхрон - что слева не синкронно тому что справа (в сером цвете)
![Screenshot from 2019-11-21 12-12-35](https://user-images.githubusercontent.com/4154978/69323875-8a969080-0c58-11ea-95de-d57371d579eb.png)

файлы 
[z.zip](https://github.com/OlehL/cuda_differ/files/3873823/z.zip)

**Comment by Alexey-T** [comment]
@kvichans FYI

**Comment by OlehL** [comment]
теперь должно бить хорошо

**Comment by OlehL** [comment]
@Alexey-T  pls test
