### ISSUE TITLE
Dialog layout

### ISSUE THREAD

**Issue by Alexey-T** [OlehL/cuda_differ#7]
неаккуратно.

- кнопки Ok/Cancel  надо сделать одной ширины (80-100) и в правый нижний угол
- кнопку browse - ту же ширину
- labels над едитами- надо по левому краю полей
- для Линукс надо пониже кнопки ok/cancel
- "Ok" -> "OK"

![screenshot from 2019-01-28 12-12-14](https://user-images.githubusercontent.com/4154978/51825632-4071a680-22f6-11e9-8bba-5e16db983991.png)

**Comment by OlehL** [comment]
fixed
