### ISSUE TITLE
LSP plugin

### ISSUE THREAD

**Issue by Alexey-T** [OlehL/cuda_differ#70]
@OlehL Все еще нужен плагин поддержки LSP (Lang Server Protocol), о плате можем поговорить в чате.

**Comment by OlehL** [comment]
Плагин сложный. Буду делать ближе под новый год.

**Comment by Alexey-T** [comment]
Ok

**Comment by Alexey-T** [comment]
Hello
как у тебя с тем плагином VSCode completions? а за LSP будем браться?

**Comment by OlehL** [comment]
VSCode completions пока делаю очень медленно. Времени нет совсем.
