### ISSUE TITLE
Bug in "Go to next difference"

### ISSUE THREAD

**Issue by Alexey-T** [OlehL/cuda_differ#71]
вот 2 файла.
[tst.zip](https://github.com/OlehL/cuda_differ/files/3952296/tst.zip)

каретка в начале d.diff, делаю Go to next diff. прыгает криво! у меня на строку 96, хотя первый дифф это строка 3 или 4, и потом еще есть до 96й.

и потом оно еще выделило чтото!

![Screenshot from 2019-12-11 22-56-24](https://user-images.githubusercontent.com/4154978/70655730-d17d1200-1c69-11ea-94dc-b0a23e1bcd6a.png)

**Comment by Alexey-T** [comment]
прыг надо делать так- ищем массив всех bookmarks с нашим тегом.
ищем еще массив gaps.
смешаниваем 2 массива. сортируем.
и прыг.

**Comment by OlehL** [comment]
ок, посмотрю

**Comment by Alexey-T** [comment]
Почему бы не вернуть весь мой код от этой команды

**Comment by OlehL** [comment]
какое поведение будет лучше:
  - прыгать по каждой измененной строке
  - прыгать по измененному блока (блок содержит группы измененных строк)

**Comment by Alexey-T** [comment]
по блоку, чтобы не мучаться.

**Comment by OlehL** [comment]
Я питался упростить код и брать измененный блоки сразу с класса Differ, так быстрее и проще чем читать апи. Сейчас после прыжка вперед/назад дополнительно выделяется измененный блок текста(если это не нужно, отключу). Доделаю отслеживание курсора, чтобы работало как надо. Баг именно в этом. 
Если необходимо, то могу вернуть твой код, но если я не ошибаюсь он прыгал по каждой измененной строке.

**Comment by Alexey-T** [comment]
Лучше сделать новый код, прыгать по блокам

**Comment by OlehL** [comment]
исправлено в 9f99f4e2a7ced81af54479fa648ed7039491a139

**Comment by Alexey-T** [comment]
Можешь написать на рус, что поменялось? я переведу

**Comment by OlehL** [comment]
history уже добавлена ранее в #76

**Comment by Alexey-T** [comment]
ааа, патч от августа.
