### ISSUE TITLE
Plugin work

### ISSUE THREAD

**Issue by Alexey-T** [OlehL/cuda_differ#72]
@OlehL 
http://synwrite.sourceforge.net/forums/viewtopic.php?f=19&t=2366

**Comment by OlehL** [comment]
После LSP будет ок? Или надо в первую очередь?

**Comment by Alexey-T** [comment]
Этот плагин легче, лучше в первую оч. Общаться с человеком на форуме , у него ещё где-то акк на гх есть

**Comment by OlehL** [comment]
ок, начну с него.

**Comment by Alexey-T** [comment]
В репо https://github.com/CudaText-addons/cuda_fountain_helper есть issue 4 - человек вроде тотже самый, если что
