### ISSUE TITLE
History?

### ISSUE THREAD

**Issue by Alexey-T** [OlehL/cuda_differ#76]
@OlehL можешь написать тут по рус, что поменялось? я напишу пач к history.txt

**Comment by OlehL** [comment]
ок, сейчас

**Comment by OlehL** [comment]
добавлено Compare with... - сравнения текущего файла с выбранным в диалоге
добавлено Select current difference - выделять текущее изменение под курсором
добавлено Focus to opposit panel  - всегда искал название системной команды когда нужно, лучше иметь под рукой
переделано Jump to next difference
переделано Jump to previous difference
переделано Copy current difference to the right
переделано Copy current difference to the left
добавлена опция enable_auto_refresh
изменена опция keep_caret_visible на enable_sync_caret
