### ISSUE TITLE
the task with the Terminal plugin

### ISSUE THREAD

**Issue by Alexey-T** [OlehL/cuda_differ#82]
@OlehL опишу что вообще за таск.
в плагине Terminal уже есть емуляция терминала. но неполная. потому что вывод команд с цветовыми кодами в Лин выводится как просто текст. там идет запуск команд и redirect to file- поэтому мы получаем из этого redirect только текст. А в VS Code Terminal (встроенный плагин в поставке) я ввожу например

$ ls -l

и это прямо в VSCode выводит с цветом (цветные имена файлов как в Баш).
таск-- сделать вывод тоже с цветом.

![vv](https://user-images.githubusercontent.com/4154978/103138240-a2550980-46e1-11eb-9c6d-034094b99b00.png)

я нашел Питон либу которая наверно может так делать. 
https://pypi.org/project/pyte/
я пытался на основе ее примера сделать. не получилось. там как-то сложно.
еще я написал в GH авторам Pyte, попросил пример. чтобы с цветом выводить.
они не дали.
вобщем наверное надо делать на Pyte. не знаю как.
на странице Pyte написано

* pyte is not alone in the weird world of terminal emulator libraries, here’s a few other options worth checking out: Termemulator, pyqonsole, webtty, AjaxTerm and of course vt102.

**Comment by OlehL** [comment]
Поищу, как такое сделать.

**Comment by Alexey-T** [comment]
@OlehL задача сделана! by @halfbrained .
