### ISSUE TITLE
Improvements

### ISSUE THREAD

**Issue by ags1234** [OlehL/cuda_differ#86]
Hello!

Thank you for this very useful plugin. Please make it work with tabs that are not saved.
Also, it would be great if your plugin would insert two options in right click menu on a tab:
- Compare with...
- Compare with active tab

In Sublime Text there is a plugin, Compare Side-By-Side, which has this and it is very easy to work with.

**Comment by Alexey-T** [comment]
~I will try to add it; I will save 2 untitled/chnaged tabs to temp files, and then call Differ code for 2 these temp files.~

Cannot promise about new items in tab-context-menu, it's not simple

**Comment by Alexey-T** [comment]
I think more. why is it needed at all to compare untitled/unsaved tabs?? why dont you save them to named files first? to support untitled tabs - it's additional work for me (or @OlehL) - we will need new dialog to choose 2 untitled tabs first, let's avoid it.

2nd reason. comparing of 2 untitled tabs (by making 2 temp files) is not handy - user will edit both sides, and these changes will not apply to original untitled tabs - they will stick to temp files. so UI is not OK here. it will be not OK.

**Comment by OlehL** [comment]
Thank you for your assessment of my work.
Currently, I have War in my country. No time for coding.  Later I'll do it.

**Comment by ags1234** [comment]
@OlehL
Oooh, I am sorry, man! I didn't know you're Ukrainian!  This war is so unfair! In a normal world it should not have happened. Are you okay?

@all
I don't know how to code. But Cuda seemed interesting and I just wanted to contribute with some of my observations, which I thought would improve Cuda. And help users on the long run. That's why I opened this thread.

I work in an environment where time matters. A lot. And it is measured in seconds. So there are times when not having to save the buffers when doing comparisons would help.

**Comment by ildarkhasanshin** [comment]
https://github.com/CudaText-addons/cuda_differ/pull/1

**Comment by Alexey-T** [comment]
@ags1234 Try the Ildar's fork.
Remove Differ first.
"Plugins / addon manager / install from github", enter URL
https://github.com/ildarkhasanshin/cuda_differ

and branch 'master'.

changes:

+ add: menu item "Compare current file with tab" to context menu of tab 
+ add: menu item "Compare current file with..." to context menu of tab

**Comment by ags1234** [comment]
Thanks! 

I followed the instructions to install and in worked. But I had to choose to download as zip.

Both the menu options appeared. After using "Compare current file with..." for comparing of two saved buffers, I get this error:

![Screenshot - 31 03 2022 , 21_46_45](https://user-images.githubusercontent.com/21011513/161128970-68895f2e-cf70-4189-b338-e6c083f37eb2.png)

**Comment by Alexey-T** [comment]
@ildarkhasanshin 

- check your code on Win
- it may be that Windows path sep `\` works as escape character in the callback. replace `\` with `\\`.

**Comment by Alexey-T** [comment]
@ags1234 
Pls try my fixed fork

- remove Differ
- do "plugins / addon manager / install from github" with URL https://github.com/CudaText-addons/cuda_differ/

**Comment by Alexey-T** [comment]
Differ is updated in the addon manager.

**Comment by ags1234** [comment]
Indeed, the error is now gone.

Is there a reason why If I compare A with B, the plugin closes one of the files, A, but leaves B open?
Shouldn't both the files A and B be left open, since this was a user action?

**Comment by Alexey-T** [comment]
@ags1234 I posted this new issue to #91 . I will reply there,  when I study this case.
