### ISSUE TITLE
UI combobox dont save items

### ISSUE THREAD

**Issue by Alexey-T** [OlehL/cuda_differ#9]
chosen items are not saved to comboboxes, next Dlg call shows empty comboboes dropdown. Linux.

**Comment by OlehL** [comment]
Сейчас в combobox items попадают файлы которие уже открытие в cudatext. Сделаю чтобы туда еще попадали файлы которие уже были открыты в текущей сесии. То есть после рестарта cudatext список будет очищаться. Так будет ОК?
