### ISSUE TITLE
on comparing from the tab context menu, one of files is left open

### ISSUE THREAD

**Issue by Alexey-T** [OlehL/cuda_differ#91]
@ags1234 wrote

> Is there a reason why If I compare A with B, the plugin closes one of the files, A, but leaves B open? Shouldn't both the files A and B be left open, since this was a user action?

**Comment by Alexey-T** [comment]
@ildarkhasanshin 
Seems we cannot close the original tab from its popup menu handler. it works only sometimes. I suggest to run a `timer_proc`, which will run the compare.

**Comment by ildarkhasanshin** [comment]
@ags1234
is it possible to record a screen recording of the error playback?

**Comment by Alexey-T** [comment]
guys,
I added the `timer_proc` to my fork,
so test again. Get the file `__init__.py` from
https://github.com/cudatext-addons/cuda_differ
and copy it over file `py/cuda_differ/__init__.py`

**Comment by ildarkhasanshin** [comment]
`callback: module=cuda_differ;cmd=compare_from_timer;info=/home/ildar/.config/cudatext/py/cuda_differ/__init__.py~~/home/ildar/.config/cudatext/py/cuda_differ/___init__.py;`

`compare_from_timer: /home/ildar/.config/cudatext/py/cuda_differ/__init__.py~~/home/ildar/.config/cudatext/py/cuda_differ/___init__.py`

**Comment by Alexey-T** [comment]
what? I disabled that 2 print messages. in the Github - already posted to GH.

**Comment by ildarkhasanshin** [comment]
how does timer_proc works? need to decrease/increase 100ms and see the result?

**Comment by Alexey-T** [comment]
1. do 'fetch from upstream' becase I renamed 'your' new names. they ware LONG
2. timer_proc-- https://wiki.freepascal.org/CudaText_API#timer_proc

**Comment by Alexey-T** [comment]
3. I just tested with small value 100. User needs to test on his system!

**Comment by ildarkhasanshin** [comment]
> 3. I just tested with small value 100. User needs to test on his system!

works for me at 10, 100, 1000, 10000

**Comment by Alexey-T** [comment]
So the value 100 is okay. 10 is too small delay for ui.

**Comment by ags1234** [comment]
> @ags1234 is it possible to record a screen recording of the error playback?

Ooh, the error from previous thread is not fixed, unfortunately. Crash appears after comparing the two files. Can someone reproduce it?

![Screenshot - 02_04](https://user-images.githubusercontent.com/21011513/161371728-bd7f8ff5-41f9-405c-a6da-1c66f50b2703.png)


Here are the files:
[a and b.zip](https://github.com/OlehL/cuda_differ/files/8402064/a.and.b.zip)

**Comment by Alexey-T** [comment]
@ags1234 

- make sure you use last Cud release 1.159.x
- make sure you got the latest Differ from https://github.com/cudatext-addons/cuda_differ - is it so??

**Comment by Alexey-T** [comment]
@ags1234

-    make sure you use last Cud release 1.159.x
-    make sure you got the latest Differ from https://github.com/cudatext-addons/cuda_differ - is it so??
-    post here in the triple ticks, content of CONSOLE panel in Cud. your screen shows it has 12 errors!

**Comment by Alexey-T** [comment]
and

- make sure 2 filenames (a and b) paths don't have weird ASCII chars, unicode chars. is it so?

**Comment by ags1234** [comment]
Ok.
Using Cuda 1.159.2 now. Was using 1.158.
Using plugin from 2022.04.01.
Path only contains English letters and spaces.
Did a few comparisons. Didn't crash.

**Comment by Alexey-T** [comment]
thanks. seems it's solved.

**Comment by ags1234** [comment]
Unfortunately this shouldn't be closed, since the problem from the first post still persists.

**Comment by Alexey-T** [comment]
@ags1234 
Okay. Did you test after my reply?

https://github.com/OlehL/cuda_differ/issues/91#issuecomment-1086192958

**Comment by Alexey-T** [comment]
Seems bug is visible on your side. Ok, can you give a video which shows all your steps?
I recommend the ScreenToGif app on windows.

can you also write steps in text, pls?

**Comment by Alexey-T** [comment]
I repeated the bug! on win10. no need in video.

**Comment by Alexey-T** [comment]
@ags1234 Pls test again, after getting plugin from
https://github.com/cudatext-addons/cuda_differ
I see it's fixed now

**Comment by ags1234** [comment]
Ok, updated plugin from master branch.
Using ScreenToGif to record Cuda. ScreenToGif is nice and it is portable, thanks for recommendation :)

![Animation3](https://user-images.githubusercontent.com/21011513/161533115-8deac515-afdd-453e-aa68-c698ef62fbc9.gif)

Now Cuda combines both files in one single tab, closing the separate tabs of files. Is this the intended behavior?

**Comment by Alexey-T** [comment]
Yes, it is as designed. Old version of Differ did the same.

**Comment by Alexey-T** [comment]
(post new reports to separate issue. closing)

**Comment by ags1234** [comment]
Ok, thank you.
